[versions]
springboot="3.4.0"
postgres="42.7.3"
flyway="11.0.1"
thymeleafLD="3.3.0"
kotlinReflect="2.1.0"
kotlinSpring="1.9.24"
kotlinNoarg="2.1.0"
jakartaValidation="3.1.0"
junitJupiter="5.11.3"
springFramework="6.2.0"
assertj="3.26.3"
testcontainers="1.20.4"
junitPlatformSuite="1.11.3"

[libraries]
sb-starter = {group="org.springframework.boot", name="spring-boot-starter", version.ref="springboot"}
sb-starter-web = {group="org.springframework.boot", name="spring-boot-starter-web", version.ref="springboot"}
sb-starter-data-jpa = {group="org.springframework.boot", name="spring-boot-starter-data-jpa", version.ref="springboot"}
sb-starter-thymeleaf={group="org.springframework.boot", name="spring-boot-starter-thymeleaf", version.ref="springboot"}
sb-starter-validation ={group="org.springframework.boot", name="spring-boot-starter-validation", version.ref="springboot"}
sb-starter-test={group="org.springframework.boot", name="spring-boot-starter-test", version.ref="springboot"}
spring-context = {group="org.springframework", name="spring-context", version.ref="springFramework"}
jetbrains-kotlin-reflect = {group="org.jetbrains.kotlin", name="kotlin-reflect", version.ref="kotlinReflect"}
thymeleafLD = {group="nz.net.ultraq.thymeleaf", name="thymeleaf-layout-dialect", version.ref="thymeleafLD"}
postgres = {group="org.postgresql", name="postgresql", version.ref="postgres"}
flywayCore = {group="org.flywaydb", name="flyway-core", version.ref="flyway"}
flywayPostgresql = {group="org.flywaydb", name="flyway-database-postgresql", version.ref="flyway"}
jakarta-validation = {group="jakarta.validation", name="jakarta.validation-api", version.ref="jakartaValidation"}
assertj = {group="org.assertj", name="assertj-core", version.ref="assertj"}
junit-jupiter = {group="org.junit.jupiter", name="junit-jupiter", version.ref="junitJupiter"}
junit-platform-suite-api = {group="org.junit.platform", name="junit-platform-suite-api", version.ref="junitPlatformSuite"}
junit-platform-suite-engine = {group="org.junit.platform", name="junit-platform-suite-engine", version.ref="junitPlatformSuite"}

# Testcontainers
testcontainers-bom = {group="org.testcontainers", name="testcontainers-bom", version.ref="testcontainers"}
testcontainers-junit = {group="org.testcontainers", name="junit-jupiter", version.ref="testcontainers"}
testcontainers-postgresql = {group="org.testcontainers", name="postgresql", version.ref="testcontainers"}


[plugins]
sb = {id="org.springframework.boot", version.ref="springboot"}
jetbrains-kotlin-spring = {id="org.jetbrains.kotlin.plugin.spring", version.ref="kotlinSpring"}
jetbrains-kotlin-noarg={id="org.jetbrains.kotlin.plugin.noarg", version.ref="kotlinNoarg"}