[versions]
springboot="3.4.0"
postgres="42.7.3"
flyway="11.0.1"
thymeleafLD="3.3.0"
kotlinReflect="2.1.0"
kotlinSpring="1.9.24"
kotlinNoarg="2.1.0"
# Testcontainers
testcontainers="1.20.4"
#lombok="1.18.36"

[libraries]
sb-starter = {group="org.springframework.boot", name="spring-boot-starter", version.ref="springboot"}
sb-starter-web = {group="org.springframework.boot", name="spring-boot-starter-web", version.ref="springboot"}
sb-starter-data-jpa = {group="org.springframework.boot", name="spring-boot-starter-data-jpa", version.ref="springboot"}
sb-starter-thymeleaf={group="org.springframework.boot", name="spring-boot-starter-thymeleaf", version.ref="springboot"}
sb-starter-validation ={group="org.springframework.boot", name="spring-boot-starter-validation", version.ref="springboot"}
sb-starter-test={group="org.springframework.boot", name="spring-boot-starter-test", version.ref="springboot"}
#sb-dev-tools = {group="org.springframework.boot", name="spring-boot-devtools", version.ref="springboot"}
thymeleafLD = {group="nz.net.ultraq.thymeleaf", name="thymeleaf-layout-dialect", version.ref="thymeleafLD"}
jetbrains-kotlin-reflect = {group="org.jetbrains.kotlin", name="kotlin-reflect", version.ref="kotlinReflect"}
postgres = {group="org.postgresql", name="postgresql", version.ref="postgres"}
flywayCore = {group="org.flywaydb", name="flyway-core", version.ref="flyway"}
flywayPostgresql = {group="org.flywaydb", name="flyway-database-postgresql", version.ref="flyway"}

# Testcontainers
testcontainers-bom = {group="org.testcontainers", name="testcontainers-bom", version.ref="testcontainers"}
testcontainers-junit = {group="org.testcontainers", name="junit-jupiter", version.ref="testcontainers"}
testcontainers-postgresql = {group="org.testcontainers", name="postgresql", version.ref="testcontainers"}


[plugins]
sb = {id="org.springframework.boot", version.ref="springboot"}
jetbrains-kotlin-spring = {id="org.jetbrains.kotlin.plugin.spring", version.ref="kotlinSpring"}
jetbrains-kotlin-noarg={id="org.jetbrains.kotlin.plugin.noarg", version.ref="kotlinNoarg"}